services:
    thunderatz.darkmode.listener:
        class: thunderatz\darkmode\event\listener
        arguments:
            - '@template'
            - '@user'
            - '@request'
        tags:
            - { name: event.listener }
